/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.AlgoritmoDijkstra;
import javax.swing.JOptionPane;

/**
 *
 * @author ggabr
 */
public class InicioSesion extends javax.swing.JFrame {
    Clases.XML regxml = new Clases.XML();

    /**
     * Creates new form Registro
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonInicio = new javax.swing.JButton();
        LateralSuperior2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NombreTexto = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        label6 = new java.awt.Label();
        IDTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 121, 57));

        BotonInicio.setBackground(new java.awt.Color(234, 215, 187));
        BotonInicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BotonInicio.setForeground(new java.awt.Color(17, 57, 70));
        BotonInicio.setText("INICIO");
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });

        LateralSuperior2.setBackground(new java.awt.Color(188, 163, 127));
        LateralSuperior2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LateralSuperior2.setForeground(new java.awt.Color(17, 57, 70));
        LateralSuperior2.setText("NOMBRE DE LA APP");
        LateralSuperior2.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 242, 216));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 821, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 625, Short.MAX_VALUE));

        NombreTexto.setBackground(new java.awt.Color(234, 215, 187));
        NombreTexto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NombreTexto.setForeground(new java.awt.Color(17, 57, 70));
        NombreTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTextoActionPerformed(evt);
            }
        });

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(new java.awt.Color(255, 242, 216));
        label4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(17, 57, 70));
        label4.setName(""); // NOI18N
        label4.setText("IDENTIFICACION");

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setBackground(new java.awt.Color(255, 242, 216));
        label6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(17, 57, 70));
        label6.setName(""); // NOI18N
        label6.setText("NOMBRE");

        IDTexto.setBackground(new java.awt.Color(234, 215, 187));
        IDTexto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        IDTexto.setForeground(new java.awt.Color(17, 57, 70));
        IDTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LateralSuperior2, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(308, 308, 308)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(NombreTexto, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                244, Short.MAX_VALUE)
                                                        .addComponent(label6,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 244,
                                                                Short.MAX_VALUE)
                                                        .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 244,
                                                                Short.MAX_VALUE)
                                                        .addComponent(IDTexto, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                244, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(337, 337, 337)
                                                .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 191,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(269, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(LateralSuperior2, javax.swing.GroupLayout.PREFERRED_SIZE, 66,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(184, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreTextoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NombreTextoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_NombreTextoActionPerformed

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonRegistroActionPerformed
        String nombre = NombreTexto.getText();
        String ID = IDTexto.getText();
    }// GEN-LAST:event_BotonRegistroActionPerformed

    private void BotonRegistroComponentAdded(java.awt.event.ContainerEvent evt) {// GEN-FIRST:event_BotonRegistroComponentAdded
        // TODO add your handling code here:
    }// GEN-LAST:event_BotonRegistroComponentAdded

    private void IDTextoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_IDTextoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_IDTextoActionPerformed

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {
        if (Clases.XML.empleadoExisteEnXML(IDTexto.getText(), NombreTexto.getText())) {
            Inicio.main(new String[] {});
        } else {
            System.out.println("USUARIO NO ENCONTRADO");
        } // GEN-FIRST:event_BotonInicioActionPerformed

    }// GEN-LAST:event_BotonInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JTextField IDTexto;
    private javax.swing.JLabel LateralSuperior2;
    private javax.swing.JTextField NombreTexto;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label4;
    private java.awt.Label label6;
    // End of variables declaration//GEN-END:variables
}
