/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.AlgoritmoDijkstra;
import javax.swing.JOptionPane;

/**
 *
 * @author ggabr
 */
public class Registro extends javax.swing.JFrame {
    Clases.XML regxml = new Clases.XML();

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonInicio = new javax.swing.JButton();
        BotonRegistro = new javax.swing.JButton();
        LateralSuperior2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NombreTexto = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        IDTexto = new javax.swing.JTextField();
        Ubicacion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 121, 57));

        BotonInicio.setBackground(new java.awt.Color(234, 215, 187));
        BotonInicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BotonInicio.setForeground(new java.awt.Color(17, 57, 70));
        BotonInicio.setText("INICIO");
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });

        BotonRegistro.setBackground(new java.awt.Color(234, 215, 187));
        BotonRegistro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BotonRegistro.setForeground(new java.awt.Color(17, 57, 70));
        BotonRegistro.setText("REGISTRO");
        BotonRegistro.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                BotonRegistroComponentAdded(evt);
            }
        });
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });

        LateralSuperior2.setBackground(new java.awt.Color(188, 163, 127));
        LateralSuperior2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LateralSuperior2.setForeground(new java.awt.Color(17, 57, 70));
        LateralSuperior2.setText("NOMBRE DE LA APP");
        LateralSuperior2.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 242, 216));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        NombreTexto.setBackground(new java.awt.Color(234, 215, 187));
        NombreTexto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NombreTexto.setForeground(new java.awt.Color(17, 57, 70));
        NombreTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTextoActionPerformed(evt);
            }
        });

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(new java.awt.Color(255, 242, 216));
        label4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(17, 57, 70));
        label4.setName(""); // NOI18N
        label4.setText("IDENTIFICACION");

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setBackground(new java.awt.Color(255, 242, 216));
        label5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(17, 57, 70));
        label5.setName(""); // NOI18N
        label5.setText("UBICACIÓN");

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setBackground(new java.awt.Color(255, 242, 216));
        label6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(17, 57, 70));
        label6.setName(""); // NOI18N
        label6.setText("NOMBRE");

        IDTexto.setBackground(new java.awt.Color(234, 215, 187));
        IDTexto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        IDTexto.setForeground(new java.awt.Color(17, 57, 70));
        IDTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextoActionPerformed(evt);
            }
        });

        Ubicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recinto", "Nodo 1", "Nodo 2", "Nodo 3", "Nodo 4", "Nodo 5", "Nodo 6", "Nodo 7", "Nodo 8", "Nodo 9", "Nodo 10", "Nodo 11", "Nodo 12", "Nodo 13", "Nodo 14", "Nodo 15", "Nodo 16", "Nodo 17", "Nodo 18", "Nodo 19", "Nodo 20", "Nodo 21", "Nodo 22", "Nodo 23", "Nodo 24", "Nodo 25", "Nodo 26", "Nodo 27", "Nodo 28", "Nodo 29" }));
        Ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbicacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BotonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addComponent(LateralSuperior2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ubicacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NombreTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(IDTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LateralSuperior2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbicacionActionPerformed
        // TODO add your handling code here:
        int origen = 0;
        String nombreOrigen;
        nombreOrigen = (String) Ubicacion.getSelectedItem();
        

        if ("Recinto".equals(nombreOrigen)) {
            origen = 0;
        }
        if ("Nodo 1".equals(nombreOrigen)) {
            origen = 1;
        }
        if ("Nodo 2".equals(nombreOrigen)) {
            origen = 2;
        }
        if ("Nodo 3".equals(nombreOrigen)) {
            origen = 3;
        }
        if ("Nodo 4".equals(nombreOrigen)) {
            origen = 4;
        }
        if ("Nodo 5".equals(nombreOrigen)) {
            origen = 5;
        }
        if ("Nodo 6".equals(nombreOrigen)) {
            origen = 6;
        }
        if ("Nodo 7".equals(nombreOrigen)) {
            origen = 7;
        }
        if ("Nodo 8".equals(nombreOrigen)) {
            origen = 8;
        }
        if ("Nodo 9".equals(nombreOrigen)) {
            origen = 9;
        }
        if ("Nodo 10".equals(nombreOrigen)) {
            origen = 10;
        }
        if ("Nodo 11".equals(nombreOrigen)) {
            origen = 11;
        }
        if ("Nodo 12".equals(nombreOrigen)) {
            origen = 12;
        }
        if ("Nodo 13".equals(nombreOrigen)) {
            origen = 13;
        }
        if ("Nodo 14".equals(nombreOrigen)) {
            origen = 14;
        }
        if ("Nodo 15".equals(nombreOrigen)) {
            origen = 15;
        }
        if ("Nodo 16".equals(nombreOrigen)) {
            origen = 16;
        }
        if ("Nodo 17".equals(nombreOrigen)) {
            origen = 17;
        }
        if ("Nodo 18".equals(nombreOrigen)) {
            origen = 18;
        }
        if ("Nodo 19".equals(nombreOrigen)) {
            origen = 19;
        }
        if ("Nodo 20".equals(nombreOrigen)) {
            origen = 20;
        }
        if ("Nodo 21".equals(nombreOrigen)) {
            origen = 21;
        }
        if ("Nodo 22".equals(nombreOrigen)) {
            origen = 22;
        }
        if ("Nodo 23".equals(nombreOrigen)) {
            origen = 23;
        }
        if ("Nodo 24".equals(nombreOrigen)) {
            origen = 24;
        }
        if ("Nodo 25".equals(nombreOrigen)) {
            origen = 25;
        }
        if ("Nodo 26".equals(nombreOrigen)) {
            origen = 26;
        }
        if ("Nodo 27".equals(nombreOrigen)) {
            origen = 27;
        }
        if ("Nodo 28".equals(nombreOrigen)) {
            origen = 28;
        }
        if ("Nodo 29".equals(nombreOrigen)) {
            origen = 29;
        }
    }//GEN-LAST:event_UbicacionActionPerformed

    private void NombreTextoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NombreTextoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_NombreTextoActionPerformed

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonRegistroActionPerformed
        String nombre = NombreTexto.getText();
        String ID = IDTexto.getText();
        String ubicacion = (String) Ubicacion.getSelectedItem();
        regxml.EscribeXML(nombre, ID, ubicacion, "driver");
    }// GEN-LAST:event_BotonRegistroActionPerformed

    private void BotonRegistroComponentAdded(java.awt.event.ContainerEvent evt) {// GEN-FIRST:event_BotonRegistroComponentAdded
        // TODO add your handling code here:
    }// GEN-LAST:event_BotonRegistroComponentAdded

    private void IDTextoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_IDTextoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_IDTextoActionPerformed

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonInicioActionPerformed
        Inicio.main(new String[] {});
    }// GEN-LAST:event_BotonInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JTextField IDTexto;
    private javax.swing.JLabel LateralSuperior2;
    private javax.swing.JTextField NombreTexto;
    private javax.swing.JComboBox<String> Ubicacion;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    // End of variables declaration//GEN-END:variables
}
