/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Ventanas;

import java.util.List;

/**
 *
 * @author ggabr
 */
public class Top5 extends javax.swing.JFrame {

    /**
     * Creates new form Top5
     */
    public Top5() {
        initComponents();
        PonerNombre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label7 = new java.awt.Label();
        Chofer1 = new java.awt.Label();
        Chofer3 = new java.awt.Label();
        Chofer2 = new java.awt.Label();
        Chofer4 = new java.awt.Label();
        Chofer5 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 242, 216));

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setBackground(new java.awt.Color(255, 242, 216));
        label7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(17, 57, 70));
        label7.setName(""); // NOI18N
        label7.setText("TOP 5 CHOFERES");

        Chofer1.setAlignment(java.awt.Label.CENTER);
        Chofer1.setBackground(new java.awt.Color(234, 215, 187));
        Chofer1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Chofer1.setForeground(new java.awt.Color(17, 57, 70));
        Chofer1.setName(""); // NOI18N
        Chofer1.setText("1");

        Chofer3.setAlignment(java.awt.Label.CENTER);
        Chofer3.setBackground(new java.awt.Color(234, 215, 187));
        Chofer3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Chofer3.setForeground(new java.awt.Color(17, 57, 70));
        Chofer3.setName(""); // NOI18N
        Chofer3.setText("3");

        Chofer2.setAlignment(java.awt.Label.CENTER);
        Chofer2.setBackground(new java.awt.Color(234, 215, 187));
        Chofer2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Chofer2.setForeground(new java.awt.Color(17, 57, 70));
        Chofer2.setName(""); // NOI18N
        Chofer2.setText("2");

        Chofer4.setAlignment(java.awt.Label.CENTER);
        Chofer4.setBackground(new java.awt.Color(234, 215, 187));
        Chofer4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Chofer4.setForeground(new java.awt.Color(17, 57, 70));
        Chofer4.setName(""); // NOI18N
        Chofer4.setText("4");

        Chofer5.setAlignment(java.awt.Label.CENTER);
        Chofer5.setBackground(new java.awt.Color(234, 215, 187));
        Chofer5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Chofer5.setForeground(new java.awt.Color(17, 57, 70));
        Chofer5.setName(""); // NOI18N
        Chofer5.setText("5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(82, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Chofer5, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Chofer4, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Chofer2, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Chofer3, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Chofer1, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Chofer1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(Chofer2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Chofer3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Chofer4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Chofer5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(29, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Chofer1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Chofer1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_Chofer1ActionPerformed

    private void Chofer5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Chofer5ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_Chofer5ActionPerformed

    private void Chofer4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Chofer4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_Chofer4ActionPerformed

    private void Chofer3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Chofer3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_Chofer3ActionPerformed

    private void Chofer2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Chofer2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_Chofer2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Top5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Top5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Top5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Top5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Top5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static java.awt.Label Chofer1;
    private static java.awt.Label Chofer2;
    private static java.awt.Label Chofer3;
    private static java.awt.Label Chofer4;
    private static java.awt.Label Chofer5;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label7;
    // End of variables declaration//GEN-END:variables

    public static void PonerNombre() {
        Chofer1.setText(Clases.XML.obtenerCalificacionesConNombresOrdenados().get(0));
        Chofer2.setText(Clases.XML.obtenerCalificacionesConNombresOrdenados().get(1));
        Chofer3.setText(Clases.XML.obtenerCalificacionesConNombresOrdenados().get(2));
        Chofer4.setText(Clases.XML.obtenerCalificacionesConNombresOrdenados().get(3));
        Chofer5.setText(Clases.XML.obtenerCalificacionesConNombresOrdenados().get(4));
    }
}
